// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PremiumForLearners.Data;

#nullable disable

namespace PremiumForLearners.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260318015609_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PremiumForLearners.Models.AcademicRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTransferRecord")
                        .HasColumnType("bit");

                    b.Property<string>("ReportCardPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("SubjectsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("AcademicRecords");
                });

            modelBuilder.Entity("PremiumForLearners.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerificationNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("PremiumForLearners.Models.Parent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("PremiumForLearners.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplyingGrade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthCertificateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Citizenship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("PreviousSchool")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialNeeds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("PremiumForLearners.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCore")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prerequisites")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Core",
                            Code = "",
                            Credits = 4,
                            Description = "",
                            Grade = "10",
                            IsActive = true,
                            IsCore = true,
                            Name = "Home Language"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Core",
                            Code = "",
                            Credits = 4,
                            Description = "",
                            Grade = "10",
                            IsActive = true,
                            IsCore = true,
                            Name = "First Additional Language"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Core",
                            Code = "",
                            Credits = 4,
                            Description = "",
                            Grade = "10",
                            IsActive = true,
                            IsCore = true,
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Core",
                            Code = "",
                            Credits = 4,
                            Description = "",
                            Grade = "10",
                            IsActive = true,
                            IsCore = true,
                            Name = "Mathematical Literacy"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Core",
                            Code = "",
                            Credits = 4,
                            Description = "",
                            Grade = "10",
                            IsActive = true,
                            IsCore = true,
                            Name = "Life Orientation"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Sciences",
                            Code = "",
                            Credits = 4,
                            Description = "",
                            Grade = "10",
                            IsActive = true,
                            IsCore = false,
                            Name = "Physical Sciences",
                            Prerequisites = "60% in Grade 9 Mathematics"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Sciences",
                            Code = "",
                            Credits = 4,
                            Description = "",
                            Grade = "10",
                            IsActive = true,
                            IsCore = false,
                            Name = "Life Sciences"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Commerce",
                            Code = "",
                            Credits = 4,
                            Description = "",
                            Grade = "10",
                            IsActive = true,
                            IsCore = false,
                            Name = "Accounting"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Commerce",
                            Code = "",
                            Credits = 4,
                            Description = "",
                            Grade = "10",
                            IsActive = true,
                            IsCore = false,
                            Name = "Business Studies"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Humanities",
                            Code = "",
                            Credits = 4,
                            Description = "",
                            Grade = "10",
                            IsActive = true,
                            IsCore = false,
                            Name = "Geography"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Humanities",
                            Code = "",
                            Credits = 4,
                            Description = "",
                            Grade = "10",
                            IsActive = true,
                            IsCore = false,
                            Name = "History"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Services",
                            Code = "",
                            Credits = 4,
                            Description = "",
                            Grade = "10",
                            IsActive = true,
                            IsCore = false,
                            Name = "Tourism"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Technology",
                            Code = "",
                            Credits = 4,
                            Description = "",
                            Grade = "10",
                            IsActive = true,
                            IsCore = false,
                            Name = "Computer Applications Tech (CAT)"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Technology",
                            Code = "",
                            Credits = 4,
                            Description = "",
                            Grade = "10",
                            IsActive = true,
                            IsCore = false,
                            Name = "Engineering Graphics & Design (EGD)"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Agriculture",
                            Code = "",
                            Credits = 4,
                            Description = "",
                            Grade = "10",
                            IsActive = true,
                            IsCore = false,
                            Name = "Agricultural Sciences"
                        });
                });

            modelBuilder.Entity("PremiumForLearners.Models.SubjectSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackupElective1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackupElective2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoreSubjects")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CounselorComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Elective1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Elective2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Elective3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Elective4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SelectionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("SubjectSelections");
                });

            modelBuilder.Entity("PremiumForLearners.Models.TransferRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpectedStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromSchool")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasAttendanceRecord")
                        .HasColumnType("bit");

                    b.Property<bool>("HasDisciplineRecord")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPreviousGrades")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReviewedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("ToSchool")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("TransferRequests");
                });

            modelBuilder.Entity("PremiumForLearners.Models.AcademicRecord", b =>
                {
                    b.HasOne("PremiumForLearners.Models.Student", "Student")
                        .WithMany("AcademicRecords")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PremiumForLearners.Models.Document", b =>
                {
                    b.HasOne("PremiumForLearners.Models.Student", "Student")
                        .WithMany("Documents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PremiumForLearners.Models.Student", b =>
                {
                    b.HasOne("PremiumForLearners.Models.Parent", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("PremiumForLearners.Models.SubjectSelection", b =>
                {
                    b.HasOne("PremiumForLearners.Models.Student", "Student")
                        .WithMany("SubjectSelections")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PremiumForLearners.Models.TransferRequest", b =>
                {
                    b.HasOne("PremiumForLearners.Models.Student", "Student")
                        .WithMany("TransferRequests")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PremiumForLearners.Models.Parent", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("PremiumForLearners.Models.Student", b =>
                {
                    b.Navigation("AcademicRecords");

                    b.Navigation("Documents");

                    b.Navigation("SubjectSelections");

                    b.Navigation("TransferRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
